name: Tests

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches: ["main", "dev"]

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'backend/pom.xml'

      - name: Build with Maven
        working-directory: ./backend
        run: mvn clean install

      - name: Run Tests
        working-directory: ./backend
        run: mvn test